### ISSUE TITLE
Bug: 御魂套装选择木魅，缺少套装数量限制

### ISSUE THREAD

**Issue by jiajunsu** [yinxin630/yys-yuhun-calculator-ui#12]
![image](https://user-images.githubusercontent.com/16359131/52180728-f7a17c80-2824-11e9-9484-a9f1ac5a971b.png)

**Comment by jiajunsu** [comment]
同类问题的还有魍魉

**Comment by yinxin630** [comment]
没明白, 麻烦详细说下

**Comment by jiajunsu** [comment]
@yinxin630  
套装限制的下拉菜单，里面有错误的数据
