### ISSUE TITLE
需求：支持有效副属性的条件筛选

### ISSUE THREAD

**Issue by jiajunsu** [yinxin630/yys-yuhun-calculator-ui#4]
effective_secondary_prop  设定御魂的有效副属性，用逗号,间隔
例如"暴击,暴击伤害,速度,攻击加成"意味着有效副属性定位为暴击、暴击伤害、速度、攻击加成

effective_secondary_prop_num 限定1-6号位御魂的有效副属性加成次数，用逗号,间隔
例如{"effective_secondary_prop": "暴击", "effective_secondary_prop_num": "5,3,5,3,5,0"}意味着1~6号位各自的有效副属性加成次数依次不少于5,3,5,3,5,0
1号位副属性暴击加成次数不少于5即暴击不低于12(2.4*5)

这个逻辑比较复杂，需要讨论下UI怎么呈现更友好

**Comment by hanooyang** [comment]
碎碎你好，根据你的需求，我有几点想法：
1. `effective_secondary_prop` 和 `effective_secondary_prop_num` 的value建议最好不要用`"5,3,5,3,5,0"`这种逗号分隔字符串的形式，程序需要多进行一次字符串split，不便于检索。个人建议使用array代替字符串。
2. 关于UI的呈现，我想能不能像游戏里边式神御魂界面那样1-6号位逆时针排布，然后用户可以通过点击各个御魂位置弹出选项menu，然后选择设置有效属性有哪些，各需要多少次加成。
3. 关于御魂加成次数，我们能够准确的算出来吗？`2.4*5` 这种算法是否是绝对准确的呢？（本人咸鱼一枚，不是很了解这个）

以上都是本人愚见，大家可以讨论一下

**Comment by jiajunsu** [comment]
http://ngabbs.com/read.php?tid=15853326

这个是之前做有效属性的想法来源。这个方式是比较难用，我们可以看看ui化怎么呈现。有必要的话，后台代码可以配合修改

**Comment by hanooyang** [comment]
我觉得可以给每一项属性一个权重值，例如： 
```
暴击：5分，攻击加成：3分
如果该御魂为 暴击5%，攻击加成8%
那么该御魂副属性得分为 5*5+ 3*8 = 49分
```

**Comment by chujie** [comment]
UI最好可以提供比较直观方便的操作，以我个人的经验这里并不需要那么复杂的设定，副属性过滤大部分时候不需要那么精确，毕竟我们不是真的要给御魂打分。从kernel大佬的帖子里来看，只需要几个常见的选项就可以了。比如，333331可能适用于大部分的场景以及御魂数并不太多的玩家。如果需要每个位置单独选择，反而变得更复杂。
所以我建议就预设高(5,3,5,3,5,3)、中(3,3,3,3,3,1)、低(3,1,3,1,3,1)三档过滤条件，以及一个自行输入的选项，可以简化实现及操作。如果以后需要更复杂的功能可以再另行加入。

**Comment by hanooyang** [comment]
不好意思，我一直以为是新做功能，为已有功能做UI的话，赞成楼上这种方式

**Comment by jiajunsu** [comment]
有效副属性筛选的UI原型，已经在win版UI上做了，可以参考

**Comment by yinxin630** [comment]
已上线
